### ISSUE TITLE
"Full, unrestricted access to thunder and your computer"

### ISSUE THREAD

**Issue by louisgag** [qiqitori/reply_as_original_recipient#9]
I was about to install from the latest git version and Thunderbird warned me about this security issue.
Would it be possible to restrain this access to something less invasive?

**Comment by qiqitori** [comment]
@louisgag  I just pushed this: https://github.com/qiqitori/reply_as_original_recipient/pull/8
Do you get the same message for the previous version?

**Comment by louisgag** [comment]
it seems to, I tried commits 4563c9a6332c8f8bd5118539314101a9eb4361d5 and 6bd93337ebc501ae062fb1be7d441e62f4c9e119 and they both do this.
Tried like this:
```
git fetch origin
git checkout origin/master
git checkout 6bd93337ebc501ae062fb1be7d441e62f4c9e119
```

**Comment by qiqitori** [comment]
Probably due to this not being a proper mail extension then I'd guess.
